### PR TITLE
Folder Rename shows current name

### PR DESCRIPTION
**Pull request by jacob13400**

### CODE REVIEW

**Comment by JithinKS97** [comment]
Thanks Jacob !!!

**Comment by JithinKS97** [comment]
@jacob13400 It would be good if you could provide a small upper margin for the text field for entering the title

**Comment by jacob13400** [comment]
Like this?

**Comment by JithinKS97** [comment]
Like what?

**Comment by jacob13400** [comment]
I sent a picture attached to the previous email.
I am sending it again.

By margin did you mean whats shown in the picture?
If not, what do you expect?

**Comment by JithinKS97** [comment]
I think I did not receive the email that you sent. Its okey. I can fix the margin myself.

**Pull request merged**
