### PR TITLE
Dashboard/Sidebar and Lesson areas responsive

### PR DESCRIPTION
**Pull request by ashneeldas2**
- The dashboard is responsive and no longer overlaps on zoom 
- The lesson area, including the YouTube embed, is now responsive.

### CODE REVIEW

**Comment by JithinKS97** [comment]
Yayyy

**Comment by JithinKS97** [comment]
Great work...The  Lessonplan creator area is also partially responsive. But the menu and slideslist are not. I think you can make them also responsive by this approach. Can you please take a look at them?

**Comment by JithinKS97** [comment]
And I think you could move the styles specific to Lessons page to a separate file which would help the could to look more organized. Can you do that?

**Comment by ashneeldas2** [comment]
Working on the Lessonplan area right now — As for moving styles, I’ve been having some trouble linking external stylesheets (for some reason, it leads to the application crashing) but once I figure that out I will copy and paste the styles into a new CSS file.

**Pull request merged**
